### ISSUE TITLE
403 forbidden for http://localhost:8080/api/v1/auth/register

### ISSUE THREAD

**Issue by codetobuild** [Ozair0/Spring-Boot-3-Auth-JWT-Cookie-JPA#1]
For the endpoint 
http://localhost:8080/api/v1/auth/register

request body {
    "first_name": "firstname",
    "last_name": "lastname",
    "email":"a@a.com",
    "roles":"ADMIN"
}

i am unable to register. Instead i got 403 resopnse on POSTMAN

**Comment by Ozair0** [comment]
You are missing the password!
try this:

```
request body {
"first_name": "firstname",
"last_name": "lastname",
"email":"a@a.com",
"password": "YourPassword123",
"roles":"ADMIN"
}
```
