### ISSUE TITLE
Authentication failed even with valid JWT token

### ISSUE THREAD

**Issue by codetobuild** [Ozair0/Spring-Boot-3-Auth-JWT-Cookie-JPA#2]
route:  http://localhost:8086/api/v1/users
user role: ROLE_ADMIN
email and password are valid
jwt token is also valid.
HTTP: GET request

I have attached "Bearer tokenstringhere" in Authorization header via postman

I am unable to access this API route even after giving a valid jwt token which I got from /api/v1/authenticate .
Please check into this issue

**Comment by codetobuild** [comment]
Please ignore the above comment. I have fixed the code. 
Kindly close this issue. Thanks.

**Comment by Ozair0** [comment]
The app uses cookie, good that your issue is fixed.
